// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

/**
 * Renderer-side view of the Overview.
 *
 * A structural mirror of `rocm_app_core::health`. Every verdict, component
 * row, freshness label, and metric arrives already derived: this module adds
 * no rules, so there is no second place where "is this healthy" is answered.
 */

import { invoke } from "@tauri-apps/api/core";
import rawFixtures from "../../fixtures/dashboard.json";
import type { EligibleAction, HealthVerdict } from "./contract";
import { requireTauri } from "./controller";
import type { DriverAdvice, Fact } from "./onboarding";

export type ComponentKind =
  | "app"
  | "cli"
  | "driver"
  | "system-hip-rocm"
  | "managed-runtime"
  | "python"
  | "py-torch"
  | "engine"
  | "unrecognised";

export type ComponentStatus =
  "ready" | "update-available" | "not-installed" | "unsupported" | "stale" | "unknown";

export interface ComponentRow {
  readonly kind: ComponentKind;
  readonly label: string;
  readonly value: string;
  readonly status: ComponentStatus;
  /** Text form of the status. Colour never carries it alone. */
  readonly statusLabel: string;
  readonly note: string | null;
}

export interface Freshness {
  readonly observedAtUnixMs: number;
  readonly ageMs: number;
  readonly stale: boolean;
  readonly label: string;
}

export interface NextStep {
  readonly label: string;
  /** `null` when the step is not a mutation — refresh, reconnect, or nothing. */
  readonly action: EligibleAction | null;
}

export type MetricValue =
  | { state: "reading"; text: string; ratio: number | null }
  | { state: "unavailable"; reason: string };

export interface MetricRow {
  readonly key: string;
  readonly label: string;
  readonly value: MetricValue;
}

export interface HistoryPoint {
  readonly atUnixMs: number;
  readonly utilizationPct: number | null;
  readonly vramUsedMb: number | null;
}

export interface TelemetryPanel {
  readonly device: string | null;
  readonly metrics: readonly MetricRow[];
  readonly history: readonly HistoryPoint[];
  readonly failure: string | null;
}

export type NoticeCode =
  | "offline"
  | "partial-probe"
  | "unsupported"
  | "untrusted-metadata"
  | "unmanaged-rocm"
  | "telemetry-permission"
  | "stale";

export interface Notice {
  readonly code: NoticeCode;
  readonly message: string;
}

export interface HealthOverview {
  readonly verdict: HealthVerdict;
  readonly verdictLabel: string;
  readonly summary: string;
  readonly nextStep: NextStep;
  readonly firstRun: boolean;
  readonly headlineFacts: readonly Fact[];
  readonly freshness: Freshness;
  readonly components: readonly ComponentRow[];
  readonly driver: DriverAdvice;
  readonly telemetry: TelemetryPanel;
  readonly notices: readonly Notice[];
}

/** A refusal the Overview could not recover from. */
export interface OverviewError {
  readonly code: string;
  readonly message: string;
}

/** Where the Overview gets its data. One seam, two implementations. */
export interface DashboardSource {
  overview(refresh: boolean): Promise<HealthOverview>;
}

export function desktopSource(): DashboardSource {
  return {
    overview: async (refresh) => {
      requireTauri();
      return await invoke<HealthOverview>("health_overview", { refresh });
    },
  };
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

export interface DashboardStateFixture {
  readonly name: string;
  readonly purpose: string;
  readonly nowUnixMs: number;
  readonly overview: HealthOverview;
}

export interface FatalFixture {
  readonly name: string;
  readonly purpose: string;
  readonly error: OverviewError;
}

export interface DashboardFixtures {
  readonly states: readonly DashboardStateFixture[];
  readonly fatal: readonly FatalFixture[];
}

/** Generated by `rocm_app_core::health`'s test suite. */
export const FIXTURES = rawFixtures as unknown as DashboardFixtures;

export function fixtureState(name: string): DashboardStateFixture {
  const found = FIXTURES.states.find((s) => s.name === name);
  if (!found) {
    throw new Error(`unknown dashboard fixture: ${name}`);
  }
  return found;
}

/** A source that replays one generated state. */
export function fixtureSource(name: string): DashboardSource {
  const state = fixtureState(name);
  return { overview: () => Promise.resolve(state.overview) };
}

/**
 * A refusal as a rejection.
 *
 * An `Error` subclass rather than a bare object: everything that catches a
 * promise expects one, and the extra `code` still travels for branching.
 */
export class OverviewFailure extends Error implements OverviewError {
  readonly code: string;

  constructor(failure: OverviewError) {
    super(failure.message);
    this.name = "OverviewFailure";
    this.code = failure.code;
  }
}

/** A source that always refuses, for the fatal-error state. */
export function failingSource(error: OverviewError): DashboardSource {
  return { overview: () => Promise.reject(new OverviewFailure(error)) };
}
