// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

/**
 * Renderer-side view of ROCm Installs.
 *
 * A structural mirror of `rocm_app_core::runtimes`. Which actions a version
 * offers, and why the others are missing, is decided in Rust and re-checked
 * there at plan time; this module renders that answer and adds no rules.
 */

import { invoke } from "@tauri-apps/api/core";
import rawFixtures from "../../fixtures/runtimes.json";
import type { Approval, ChangePlan, OperationRequest, ProgressEvent } from "./controller";
import * as controller from "./controller";

export type RowAction = "activate" | "remove" | "validate" | "update";

export type BlockReason =
  | "active"
  | "previous"
  | "protected"
  | "ambiguous"
  | "unknown"
  | "unvalidated"
  | "unsupported-host"
  | "not-offered";

export interface BlockedAction {
  readonly action: RowAction;
  readonly reason: BlockReason;
}

export type Compatibility =
  { state: "matches" } | { state: "mismatched"; builtFor: string } | { state: "unknown" };

export type CheckState = "passed" | "failed" | "not-checked" | "unrecognised";

export interface RuntimeRow {
  readonly title: string;
  readonly version: string;
  readonly badges: readonly string[];
  readonly compatibility: Compatibility;
  readonly check: CheckState;
  readonly checkLabel: string;
  readonly disk: string | null;
  readonly actions: readonly RowAction[];
  readonly blocked: readonly BlockedAction[];
  /** Advanced identifiers. Shown only behind the details disclosure. */
  readonly key: string;
  readonly channel: string;
  readonly family: string;
  readonly format: string;
  readonly installRoot: string;
  readonly source: string;
}

export type UpdateStanding =
  | { state: "up-to-date"; installed: string }
  | { state: "available"; installed: string; latest: string }
  | { state: "ahead-of-index"; installed: string; latest: string }
  | { state: "offline"; detail: string }
  | { state: "stale"; installed: string; checkedAtUnixMs: number }
  | { state: "untrusted"; detail: string }
  | { state: "incompatible"; latest: string; builtFor: string }
  | { state: "not-applicable" }
  | { state: "unrecognised" };

export interface RuntimesView {
  readonly rows: readonly RuntimeRow[];
  readonly update: UpdateStanding;
  readonly updateMessage: string;
  readonly updateRequest: OperationRequest | null;
  readonly mutable: boolean;
}

/** Plain-language explanation for a missing control. */
export const BLOCK_MESSAGES: Readonly<Record<BlockReason, string>> = {
  active: "This is the version ROCm is using now.",
  previous: "This is the version ROCm falls back to. Choose another version first.",
  protected: "This version was not installed by ROCm App.",
  ambiguous: "More than one installed version answers to this name, so ROCm App will not guess.",
  unknown: "ROCm App does not have enough information about this version.",
  unvalidated: "This version has not passed its check yet.",
  "unsupported-host": "ROCm App cannot change anything on this computer.",
  "not-offered": "The ROCm tool did not offer this on this computer.",
};

/** What the Installs route needs from the outside world. */
export interface RuntimesBackend {
  view(refresh: boolean): Promise<RuntimesView>;
  plan(request: OperationRequest): Promise<ChangePlan>;
  execute(approval: Approval, onEvent: (event: ProgressEvent) => void): Promise<void>;
  cancel(): Promise<void>;
}

export function desktopRuntimes(): RuntimesBackend {
  return {
    view: async (refresh) => {
      controller.requireTauri();
      return await invoke<RuntimesView>("runtimes_view", { refresh });
    },
    plan: async (request) => await controller.plan(request),
    execute: async (approval, onEvent) => {
      await controller.execute(approval, onEvent);
    },
    cancel: controller.cancel,
  };
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

export interface AuditRecord {
  readonly atUnixMs: number;
  readonly operation: string;
  readonly planId: string;
  readonly outcome: "started" | "completed" | "cancelled" | "failed";
  readonly errorCode: string | null;
}

export interface RuntimesStateFixture {
  readonly name: string;
  readonly purpose: string;
  readonly view: RuntimesView;
}

export interface OutcomeFixture {
  readonly name: string;
  readonly events: readonly ProgressEvent[];
}

export interface RuntimesFixtures {
  readonly states: readonly RuntimesStateFixture[];
  /** The activation plan the review screen renders, from the real controller. */
  readonly plan: ChangePlan;
  readonly outcomes: readonly OutcomeFixture[];
  readonly audit: readonly AuditRecord[];
}

/** Generated by `rocm_app_core::runtimes`' test suite. */
export const FIXTURES = rawFixtures as unknown as RuntimesFixtures;

export function fixtureState(name: string): RuntimesStateFixture {
  const found = FIXTURES.states.find((s) => s.name === name);
  if (!found) {
    throw new Error(`unknown runtimes fixture: ${name}`);
  }
  return found;
}

/** Records what the screen asked the backend to do. */
export interface RuntimesCalls {
  readonly plans: OperationRequest[];
  readonly executions: Approval[];
}

export interface FixtureRuntimes extends RuntimesBackend {
  readonly calls: RuntimesCalls;
}

/**
 * A backend that replays a generated state.
 *
 * `plan` refuses by default, because the states these fixtures describe are
 * mostly ones where planning *should* be refused; a test that wants the happy
 * path passes a plan in explicitly.
 */
export function fixtureOutcome(name: string): readonly ProgressEvent[] {
  const found = FIXTURES.outcomes.find((o) => o.name === name);
  if (!found) {
    throw new Error(`unknown runtimes outcome fixture: ${name}`);
  }
  return found.events;
}

export function fixtureRuntimes(
  name: string,
  options: { readonly plan?: ChangePlan; readonly events?: readonly ProgressEvent[] } = {},
): FixtureRuntimes {
  const state = fixtureState(name);
  const calls: RuntimesCalls = { plans: [], executions: [] };
  return {
    calls,
    view: () => Promise.resolve(state.view),
    plan: (request) => {
      calls.plans.push(request);
      return options.plan
        ? Promise.resolve(options.plan)
        : Promise.reject(new Error("this fixture has no plan"));
    },
    execute: (approval, onEvent) => {
      calls.executions.push(approval);
      for (const event of options.events ?? []) {
        onEvent(event);
      }
      return Promise.resolve();
    },
    cancel: () => Promise.resolve(),
  };
}
