// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

/**
 * Renderer-side view of the tray monitor.
 *
 * A structural mirror of `rocm_app_core::tray`. The status word, the reason,
 * every menu entry and the one hand-off each state offers are all decided in
 * Rust; this module renders that answer and adds no rules. In particular the
 * compact window can only *read* and *navigate* — the tray never grew a second
 * place where ROCm can be changed.
 */

import { invoke } from "@tauri-apps/api/core";
import rawFixtures from "../../fixtures/tray.json";
import { requireTauri } from "./controller";

export type TrayStatus =
  "checking" | "healthy" | "unknown" | "setup-required" | "attention" | "unsupported" | "error";

/** A surface of the main window that a tray hand-off can open. */
export type FullSurface = "dashboard" | "onboarding" | "runtimes";

export interface QuickAction {
  readonly label: string;
  /** Where the hand-off lands. The compact window never acts on its own. */
  readonly opens: FullSurface;
}

export interface QuickStatus {
  readonly status: TrayStatus;
  /** Text form of the status. Colour never carries it alone. */
  readonly statusLabel: string;
  readonly gpu: string;
  readonly rocmVersion: string;
  readonly lastCheck: string;
  readonly reason: string;
  readonly action: QuickAction | null;
}

/**
 * Serde's externally tagged form, as it actually arrives: the unit variants
 * are bare strings and only `check` carries a payload object.
 */
export type MenuKind =
  "label" | "action" | "separator" | { readonly check: { readonly checked: boolean } };

export interface MenuEntry {
  readonly id: string;
  readonly text: string;
  readonly kind: MenuKind;
  readonly enabled: boolean;
}

export interface TrayView {
  readonly status: TrayStatus;
  readonly shortStatus: string;
  readonly tooltip: string;
  readonly items: readonly MenuEntry[];
}

export interface AutostartState {
  readonly enabled: boolean;
  /** `false` on a host with no login-item mechanism this app can use. */
  readonly available: boolean;
  /** Already user-facing prose from Rust. Rendered verbatim. */
  readonly detail: string;
}

/** What the tray surfaces need from the outside world. */
export interface TrayBackend {
  quickStatus(): Promise<QuickStatus>;
  autostart(): Promise<AutostartState>;
  setAutostart(enabled: boolean): Promise<AutostartState>;
  openFull(surface?: FullSurface): Promise<void>;
  /** Dismiss the compact window; Esc calls this. */
  hideQuick(): Promise<void>;
}

export function desktopTray(): TrayBackend {
  return {
    quickStatus: async () => {
      requireTauri();
      return await invoke<QuickStatus>("tray_quick_status");
    },
    autostart: async () => {
      requireTauri();
      return await invoke<AutostartState>("tray_autostart_state");
    },
    setAutostart: async (enabled) => {
      requireTauri();
      return await invoke<AutostartState>("tray_set_autostart", { enabled });
    },
    // The key is omitted rather than sent as `undefined`, so the command's
    // `Option<FullSurface>` reliably arrives as `None` and Rust leaves the
    // main window on whichever surface it was already showing.
    openFull: async (surface) => {
      requireTauri();
      await invoke("tray_open_full", surface === undefined ? {} : { surface });
    },
    hideQuick: async () => {
      requireTauri();
      await invoke("tray_hide_quick");
    },
  };
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

export interface TrayStateFixture {
  readonly name: string;
  readonly description: string;
  readonly windows: TrayView;
  readonly linux: TrayView;
  readonly quick: QuickStatus;
}

export interface TrayFixtures {
  readonly states: readonly TrayStateFixture[];
  /** Enabled, disabled, and unavailable, in that order. */
  readonly autostart: readonly AutostartState[];
}

/** Generated by `rocm_app_core::tray`' test suite. */
export const FIXTURES = rawFixtures as unknown as TrayFixtures;

export function fixtureState(name: string): TrayStateFixture {
  const found = FIXTURES.states.find((s) => s.name === name);
  if (!found) {
    const known = FIXTURES.states.map((s) => s.name).join(", ");
    throw new Error(`unknown tray fixture: ${name} (known states: ${known})`);
  }
  return found;
}

export function fixtureQuickStatus(name: string): QuickStatus {
  return fixtureState(name).quick;
}

export function fixtureAutostart(index: number): AutostartState {
  const found = FIXTURES.autostart[index];
  if (!found) {
    throw new Error(
      `unknown tray autostart fixture: ${index} (0..${FIXTURES.autostart.length - 1})`,
    );
  }
  return found;
}

/**
 * Records what the screen asked the backend to do.
 *
 * Exhaustive on purpose: the claim that the compact window cannot change
 * anything is only checkable if every call it can make is written down here.
 */
export interface TrayCalls {
  readonly reads: ("quickStatus" | "autostart")[];
  /** Each hand-off. `undefined` means "just show the main window". */
  readonly opened: (FullSurface | undefined)[];
  /** Autostart writes — the only mutation any tray surface can perform. */
  readonly setAutostart: boolean[];
  /** Dismissals — a window hide, which changes nothing on the machine. */
  hidden: number;
}

export interface FixtureTray extends TrayBackend {
  readonly calls: TrayCalls;
}

/**
 * A backend that replays a generated state.
 *
 * `setAutostart` answers with the seeded state whatever it was asked for,
 * because that is the shape of the real command: the operating system gets the
 * last word and reports what it actually did. A screen that echoes the click
 * instead of the answer cannot show a refused change, so the fixture makes
 * that failure visible rather than convenient.
 */
export function fixtureTray(
  name: string,
  options: {
    readonly autostart?: AutostartState | undefined;
    readonly failAutostart?: boolean | undefined;
  } = {},
): FixtureTray {
  const quick = fixtureQuickStatus(name);
  const autostart = options.autostart ?? fixtureAutostart(1);
  const calls: TrayCalls = { reads: [], opened: [], setAutostart: [], hidden: 0 };
  return {
    calls,
    quickStatus: () => {
      calls.reads.push("quickStatus");
      return Promise.resolve(quick);
    },
    autostart: () => {
      calls.reads.push("autostart");
      return Promise.resolve({ ...autostart });
    },
    setAutostart: (enabled) => {
      calls.setAutostart.push(enabled);
      return options.failAutostart === true
        ? Promise.reject(new Error("this computer refused to change the startup setting"))
        : Promise.resolve({ ...autostart });
    },
    openFull: (surface) => {
      calls.opened.push(surface);
      return Promise.resolve();
    },
    hideQuick: () => {
      calls.hidden += 1;
      return Promise.resolve();
    },
  };
}
